/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tampilanloginn;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author Fahri
 */
public class dataproduk extends javax.swing.JPanel {

    /**
     * Creates new form dataproduk
     */
    public dataproduk() {
        initComponents();
        viewDataProduk("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_utama = new javax.swing.JPanel();
        panel_dataproduk = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        btn_hps = new javax.swing.JButton();
        btn_tmbh1 = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panel_tambahh = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtstok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbkat = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsupplier = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txthj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txthb = new javax.swing.JTextField();
        panel_editt = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_batal1 = new javax.swing.JButton();
        btn_simpan1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtstok1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbkat1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtnama1 = new javax.swing.JTextField();
        txtid1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtsupplier1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txthj1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txthb1 = new javax.swing.JTextField();
        btncekid = new javax.swing.JButton();
        btnceknama = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panel_utama.setLayout(new java.awt.CardLayout());

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_produk", "no", "nama produk", "stok", "supplier", "kategori", "harga beli", "harga jual"
            }
        ));
        jScrollPane1.setViewportView(tabeldata);
        if (tabeldata.getColumnModel().getColumnCount() > 0) {
            tabeldata.getColumnModel().getColumn(7).setResizable(false);
        }

        btn_hps.setText("Hapus");
        btn_hps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hpsActionPerformed(evt);
            }
        });

        btn_tmbh1.setText("Tambah");
        btn_tmbh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tmbh1ActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel1.setText("DATA PRODUK");

        txt_cari.setText("Cari");
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-24.png"))); // NOI18N

        javax.swing.GroupLayout panel_dataprodukLayout = new javax.swing.GroupLayout(panel_dataproduk);
        panel_dataproduk.setLayout(panel_dataprodukLayout);
        panel_dataprodukLayout.setHorizontalGroup(
            panel_dataprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dataprodukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dataprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_dataprodukLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_dataprodukLayout.createSequentialGroup()
                        .addComponent(btn_tmbh1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hps, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(183, 183, 183)
                        .addComponent(txt_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addComponent(jScrollPane1)))
        );
        panel_dataprodukLayout.setVerticalGroup(
            panel_dataprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dataprodukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dataprodukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txt_cari)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_hps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tmbh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );

        panel_utama.add(panel_dataproduk, "card2");

        panel_tambahh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel2.setText("TAMBAH PRODUK");
        panel_tambahh.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        panel_tambahh.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 50, -1, -1));

        btn_simpan.setBackground(new java.awt.Color(0, 51, 255));
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        panel_tambahh.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("STOK");
        panel_tambahh.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 202, 88, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("SUPPLIER");
        panel_tambahh.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 585, -1));

        txtstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstokActionPerformed(evt);
            }
        });
        panel_tambahh.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 228, 450, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("KATEGORI");
        panel_tambahh.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 84, 23));

        cmbkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Alat Mandi", "Perawatan Pribadi", " " }));
        cmbkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkatActionPerformed(evt);
            }
        });
        panel_tambahh.add(cmbkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 194, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("NAMA PRODUK");
        panel_tambahh.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 139, 831, -1));

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        panel_tambahh.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 165, 448, 31));
        panel_tambahh.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 105, 447, 28));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("ID PRODUK");
        panel_tambahh.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 79, -1, -1));

        txtsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplierActionPerformed(evt);
            }
        });
        panel_tambahh.add(txtsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 450, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("HARGA BELI");
        panel_tambahh.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 348, -1));

        txthj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthjActionPerformed(evt);
            }
        });
        panel_tambahh.add(txthj, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 302, 24));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("HARGA JUAL");
        panel_tambahh.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 256, -1));

        txthb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthbActionPerformed(evt);
            }
        });
        panel_tambahh.add(txthb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 215, 24));

        panel_utama.add(panel_tambahh, "card2");

        panel_editt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel3.setText("EDIT PRODUK");
        panel_editt.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        btn_batal1.setText("Batal");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });
        panel_editt.add(btn_batal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 62, 91, -1));

        btn_simpan1.setBackground(new java.awt.Color(0, 51, 255));
        btn_simpan1.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan1.setText("Simpan");
        btn_simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan1ActionPerformed(evt);
            }
        });
        panel_editt.add(btn_simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 62, 91, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("STOK");
        panel_editt.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 238, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("SUPPLIER");
        panel_editt.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 308, -1, -1));

        txtstok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstok1ActionPerformed(evt);
            }
        });
        panel_editt.add(txtstok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 270, 484, 32));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("KATEGORI");
        panel_editt.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 380, -1, -1));

        cmbkat1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Alat Mandi", "Perawatan Pribadi", " " }));
        cmbkat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkat1ActionPerformed(evt);
            }
        });
        panel_editt.add(cmbkat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 380, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("NAMA PRODUK");
        panel_editt.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 165, -1, -1));

        txtnama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnama1ActionPerformed(evt);
            }
        });
        panel_editt.add(txtnama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 192, 484, 32));
        panel_editt.add(txtid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 123, 484, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("ID PRODUK");
        panel_editt.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 97, -1, -1));

        txtsupplier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupplier1ActionPerformed(evt);
            }
        });
        panel_editt.add(txtsupplier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 330, 485, 32));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("HARGA BELI");
        panel_editt.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 420, -1, -1));

        txthj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthj1ActionPerformed(evt);
            }
        });
        panel_editt.add(txthj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 458, 287, 32));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("HARGA JUAL");
        panel_editt.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 420, -1, -1));

        txthb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthb1ActionPerformed(evt);
            }
        });
        panel_editt.add(txthb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 458, 287, 32));

        btncekid.setText("CEK ID");
        btncekid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekidActionPerformed(evt);
            }
        });
        panel_editt.add(btncekid, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 124, 90, 29));

        btnceknama.setText("CEK NAMA");
        btnceknama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceknamaActionPerformed(evt);
            }
        });
        panel_editt.add(btnceknama, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 191, -1, 35));

        panel_utama.add(panel_editt, "card2");

        add(panel_utama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hpsActionPerformed
        // TODO add your handling code here:
        int n = tabeldata.getSelectedRow();
        if(n != -1){
            int id = Integer.parseInt(tabeldata.getValueAt(n, 0).toString());

            int pilihan = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin untuk menghapus data produk ini?",
                "Hapus Data",JOptionPane.YES_NO_OPTION);
            if(pilihan == 0){
                //yes
                String Q = "DELETE FROM produk WHERE id_produk="+id+" ";
                try {
                    Connection K = Config.configDB();
                    Statement S = K.createStatement();
                    S.executeUpdate(Q);
                    viewDataProduk("");
                    //format tanggal
                    Date d = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy H:m:s z");
                    String tanggal = sdf.format(d);


                    function.logActivity("\n["+tanggal+"] Hapus user berhasil "); 
//                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                    btn_hps.requestFocus();
                } catch (Exception e) {
                }
            }else {
                //no
            }
        }
    }//GEN-LAST:event_btn_hpsActionPerformed

    private void btn_tmbh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tmbh1ActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.repaint();
        panel_utama.revalidate();

        panel_utama.add(panel_tambahh);
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_btn_tmbh1ActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.repaint();
        panel_utama.revalidate();

        panel_utama.add(panel_editt);
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        txt_cari.setText("");
        viewDataProduk("");
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:
        String key = txt_cari.getText();
        String w = "WHERE "
        + "nama_produk LIKE '%"+key+"%' "
        + "OR supplier LIKE '%"+key+"%' "
        + "OR kategori LIKE '%"+key+"%' ";
        viewDataProduk(w);
    }//GEN-LAST:event_txt_cariKeyReleased

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void cmbkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkatActionPerformed

    private void txtstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtid.getText());
        String name = txtnama.getText();
        String stok = txtstok.getText();
        String supplier = txtsupplier.getText();
        String kategori = cmbkat.getSelectedItem().toString();
        String hrgbeli = txthb.getText();
        String hrgjual = txthj.getText();

        try {
            Connection K = Config.configDB(); // Pastikan koneksi ke database berhasil

            if (K == null) {
                JOptionPane.showMessageDialog(this, "Koneksi ke database gagal.");
                return; // Hentikan eksekusi jika koneksi gagal
            }

            String Q = "INSERT INTO produk (id_produk, nama_produk, stok, supplier, kategori, harga_beli, harga_jual) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement PS = K.prepareStatement(Q);

            PS.setInt(1, id);
            PS.setString(2, name);
            PS.setString(3, stok);
            PS.setString(4, supplier);
            PS.setString(5, kategori);
            PS.setString(6, hrgbeli);
            PS.setString(7, hrgjual);

            PS.executeUpdate();

            // Tampilkan pesan berhasil
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

            // Memanggil metode untuk memperbarui data di tabel jika sudah diimplementasikan
            viewDataProduk("");
            txtnama.requestFocus();
            //format tanggal
                    Date d = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy H:m:s z");
                    String tanggal = sdf.format(d);


                    function.logActivity("\n["+tanggal+"] Menambahkan data user berhasil "); 
//                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                    panel_tambahh.requestFocus();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.add(panel_dataproduk);
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txtsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplierActionPerformed

    private void txthjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthjActionPerformed

    private void txthbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthbActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.add(panel_dataproduk);
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void btn_simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan1ActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtid1.getText());
        String name = txtnama1.getText();
        String stok = txtstok1.getText();
        String supplier = txtsupplier1.getText();
        String kategori = cmbkat1.getSelectedItem().toString();
        String hrgbeli = txthb1.getText();
        String hrgjual = txthj1.getText();
    
    // Query SQL untuk mengupdate data
       String query = "UPDATE produk SET nama_produk=?, stok=?, supplier=?, kategori=?, harga_beli=?, harga_jual=? WHERE id_produk = ?";
    
        try {
        // Membuat koneksi dan PreparedStatement
            Connection conn = Config.configDB();
            PreparedStatement PS = conn.prepareStatement(query);

            // Mengatur nilai pada query
            PS.setString(1, name);
            PS.setString(2, stok);
            PS.setString(3, supplier);
            PS.setString(4, kategori);
            PS.setString(5, hrgbeli);
            PS.setString(6, hrgjual);
            PS.setInt(7, id);    // ID yang menjadi acuan untuk update

            // Eksekusi query
            int res = PS.executeUpdate();

            // Periksa hasil eksekusi
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
                viewDataProduk("");
                txtnama1.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Data gagal diubah!");
            }
            //format tanggal
                    Date d = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy H:m:s z");
                    String tanggal = sdf.format(d);


                    function.logActivity("\n["+tanggal+"] Edit data user berhasil "); 
//                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                    panel_editt.requestFocus();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_simpan1ActionPerformed

    private void txtstok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstok1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstok1ActionPerformed

    private void cmbkat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkat1ActionPerformed

    private void txtnama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnama1ActionPerformed

    private void txtsupplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupplier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsupplier1ActionPerformed

    private void txthj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthj1ActionPerformed

    private void txthb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthb1ActionPerformed

    private void btncekidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekidActionPerformed
        // TODO add your handling code here:
        try {
            Connection K = Config.configDB();
            Statement S = K.createStatement();
            String Q = "Select * from produk" + " where id_produk='" + txtid1.getText() + "'";
            ResultSet R = S.executeQuery(Q);

            if (R.next()) {
                btn_simpan.setEnabled(true);
                txtnama1.setText(R.getString("nama_produk"));
                txtstok1.setText(R.getString("stok"));
                txtsupplier1.setText(R.getString("supplier"));
                cmbkat1.setSelectedItem(R.getString("kategori"));
                txthb1.setText(R.getString("harga_beli"));
                txthj1.setText(R.getString("harga_jual"));
                txtid1.setText(R.getString("id_produk"));
            } else {
                JOptionPane.showMessageDialog(this, "ID: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                btn_simpan.setEnabled(false);
                txtnama1.setText("");
                txtstok1.setText("");
                txtsupplier1.setText("");
                cmbkat1.setSelectedItem("");
                txthb1.setText("");
                txthj1.setText("");
                txtid1.setText("");
                txtid1.requestFocus();

            }
        }catch (Exception e) {
            System.out.println("Koneksi GAGAL" + e.toString());
        }
    }//GEN-LAST:event_btncekidActionPerformed

    private void btnceknamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceknamaActionPerformed
        // TODO add your handling code here:
        try {
            Connection K = Config.configDB();
            Statement S = K.createStatement();
            String Q = ("Select * from produk" + " where nama_produk like('%"+txtnama1.getText()+"%')");
            ResultSet R = S.executeQuery(Q);

            if (R.next()) {
                btn_simpan.setEnabled(true);
                txtnama1.setText(R.getString("nama_produk"));
                txtstok1.setText(R.getString("stok"));
                txtsupplier1.setText(R.getString("supplier"));
                cmbkat1.setSelectedItem(R.getString("kategori"));
                txthb1.setText(R.getString("harga_beli"));
                txthj1.setText(R.getString("harga_jual"));
                txtid1.setText(R.getString("id_produk"));
            } else {
                JOptionPane.showMessageDialog(this, "Nama: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                btn_simpan.setEnabled(false);
                txtnama1.setText("");
                txtstok1.setText("");
                txtsupplier1.setText("");
                cmbkat1.setSelectedItem("");
                txthb1.setText("");
                txthj1.setText("");
                txtid1.setText("");
                txtid1.requestFocus();

            }
        }catch (Exception e) {
            System.out.println("Koneksi GAGAL" + e.toString());
        }
    }//GEN-LAST:event_btnceknamaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_batal1;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hps;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_simpan1;
    private javax.swing.JButton btn_tmbh1;
    private javax.swing.JButton btncekid;
    private javax.swing.JButton btnceknama;
    private javax.swing.JComboBox<String> cmbkat;
    private javax.swing.JComboBox<String> cmbkat1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_dataproduk;
    private javax.swing.JPanel panel_editt;
    private javax.swing.JPanel panel_tambahh;
    private javax.swing.JPanel panel_utama;
    private static javax.swing.JTable tabeldata;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txthb;
    private javax.swing.JTextField txthb1;
    private javax.swing.JTextField txthj;
    private javax.swing.JTextField txthj1;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnama1;
    private javax.swing.JTextField txtstok;
    private javax.swing.JTextField txtstok1;
    private javax.swing.JTextField txtsupplier;
    private javax.swing.JTextField txtsupplier1;
    // End of variables declaration//GEN-END:variables
    public static void viewDataProduk(String where) {
        try {
            DefaultTableModel m = (DefaultTableModel) tabeldata.getModel();
            m.getDataVector().removeAllElements();
            Connection K = Config.configDB();
            Statement S = K.createStatement();
            String Q = "SELECT * FROM produk "+where;
            ResultSet R = S.executeQuery(Q);
            int n = 1;
            while (R.next()) {                 
                int id = R.getInt("id_produk");
                String nama = R.getString("nama_produk");
                String stok = R.getString("stok");
                String supplier = R.getString("supplier");
                String kategori = R.getString("kategori");
                String hrgbeli = R.getString("harga_beli");
                String hrgjual = R.getString("harga_jual");
                Object[] data = {id,n,  nama, stok, supplier, kategori, hrgbeli, hrgjual};
                m.addRow(data);
                n++;
            }
            
            tabeldata.getColumnModel().getColumn(0).setMinWidth(0);
            tabeldata.getColumnModel().getColumn(0).setMaxWidth(0);
            
        } catch (Exception e) {
            //error handling
        }
    }
}
