/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilanloginn;

import javax.swing.JFrame;
import tampilanloginn.Profile;

/**
 *
 * @author Lenovo
 */
public class menu extends javax.swing.JFrame {
        Profile p;

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
//    public menu(Profile P) {
//        initComponents();
//
//        
//        this.p = P;
//        lb_nama.setText(p.getFullname().toUpperCase());
//        lb_level.setText(p.getLevel().toUpperCase());
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_sidebar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pn_content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_sidebar.setBackground(new java.awt.Color(204, 255, 255));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(225, 369));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        home.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/png-transparent-menu-icon-icon-design-hamburger-button-house-css-sprites-user-interface-home-page-triangle-removebg-preview (1) (1) (1) (1) (1).png"))); // NOI18N
        home.setText("  Menu");
        home.setPreferredSize(new java.awt.Dimension(56, 21));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        jLabel1.setText("    MAM SHOP");

        datauser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        datauser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datauser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/png-transparent-account-cloud-database-person-profile-storage-user-cloud-computing-data-storage-icon-removebg-preview (1) (1).png"))); // NOI18N
        datauser.setText("  Data User");
        datauser.setPreferredSize(new java.awt.Dimension(56, 21));
        datauser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datauserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datauserMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                datauserMousePressed(evt);
            }
        });

        dataproduk.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dataproduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kisspng-computer-icons-food-restaurant-clip-art-picknick-5b2354f2e5eaf6.2213585115290421629418-removebg-preview (1) (2).png"))); // NOI18N
        dataproduk.setText("   Produk");
        dataproduk.setPreferredSize(new java.awt.Dimension(56, 21));
        dataproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataprodukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataprodukMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dataprodukMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("SELAMAT DATANG");

        jLabel3.setText("NAMA");

        jLabel4.setText("JABATAN");

        jLabel5.setText(":");

        jLabel6.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(datauser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataproduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(lb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6))
                    .addComponent(lb_level, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datauser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sidebarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        pn_content.setBackground(new java.awt.Color(255, 255, 255));
        pn_content.setPreferredSize(new java.awt.Dimension(513, 100));
        pn_content.setLayout(new javax.swing.BoxLayout(pn_content, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(737, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void datauserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserMouseClicked
        // TODO add your handling code here:
        pn_content.removeAll();
        pn_content.add(new datauser());
        pn_content.repaint();
        pn_content.revalidate();
        
//        Tampilandatauser T = new Tampilandatauser();
//        T.setVisible(true);
       
    }//GEN-LAST:event_datauserMouseClicked

    private void datauserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_datauserMouseEntered

    private void datauserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datauserMousePressed
        // TODO add your handling code here:
//        panel_utama.removeAll();
//        panel_utama.add(new Tampilandatauserr());
//        panel_utama.repaint();
//        panel_utama.revalidate();
    }//GEN-LAST:event_datauserMousePressed

    private void dataprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataprodukMouseClicked
        // TODO add your handling code here:
        pn_content.removeAll();
        pn_content.add(new dataproduk());
        pn_content.repaint();
        pn_content.revalidate();
    }//GEN-LAST:event_dataprodukMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        pn_content.removeAll();
        pn_content.add(new contentbg());
        pn_content.repaint();
        pn_content.revalidate();
    }//GEN-LAST:event_homeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pn_content.add(new contentbg());
        pn_content.repaint();
        pn_content.revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void dataprodukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataprodukMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dataprodukMouseEntered

    private void dataprodukMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataprodukMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataprodukMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel dataproduk = new javax.swing.JLabel();
    public static final javax.swing.JLabel datauser = new javax.swing.JLabel();
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static final javax.swing.JLabel lb_level = new javax.swing.JLabel();
    public static final javax.swing.JLabel lb_nama = new javax.swing.JLabel();
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_sidebar;
    // End of variables declaration//GEN-END:variables
}
